In [1]:
import pandas as pd

file = r"E:\NUS\galaxy\rc3\asu2.tsv"

# 读入，分号分隔，跳过注释行
rc3 = pd.read_csv(file, sep=";", comment="#")

# 强制把 RA/DEC 转换成 float，不可转换的变 NaN
rc3["_RAJ2000"] = pd.to_numeric(rc3["_RAJ2000"], errors="coerce")
rc3["_DEJ2000"] = pd.to_numeric(rc3["_DEJ2000"], errors="coerce")

# 丢掉无效行
rc3 = rc3.dropna(subset=["_RAJ2000", "_DEJ2000"]).reset_index(drop=True)

print(rc3.head())

   _RAJ2000   _DEJ2000      RA2000     DE2000          altname          PGC  \
0  0.007852  47.274382  00 00 01.8  +47 16 28   UGC 12889       PGC    2
1  0.036593  -6.374703  00 00 08.7  -06 22 29   MCG -1- 1- 16   PGC   12
2  0.089093  -2.610543  00 00 21.3  -02 36 38   MCG -1- 1- 20   PGC   23
3  0.094195 -80.791574  00 00 22.5  -80 47 30   ESO   12- 12    PGC   30
4  0.100348  39.499948  00 00 24.0  +39 30 00   UGC 12894       PGC   35

      type     T    D25    R25     BT BT_code     cz
0  .SBT3..   3.0   1.33   0.07                   NaN
1  .S..1P?   1.0   1.18   0.74                  6493
2  .E+..*.  -4.0   1.15   0.25                   NaN
3  PSXT4P.   4.0   1.19   0.07                  7900
4  .I..9..  10.0   0.96   0.00                   NaN

In [2]:
# === Cell 1: imports & paths ===
import os, re, math, numpy as np, pandas as pd, requests
from astropy.io import fits
from astropy.wcs import WCS
from astropy.wcs.utils import proj_plane_pixel_scales

# 你的路径
rc3_tsv   = r"E:\NUS\galaxy\rc3\asu2.tsv"             # RC3 TSV (VizieR 导出)
outdir    = r"E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4" # 新的输出目录
report_csv = r"E:\NUS\galaxy\rc3\centered_check_report3.csv"
os.makedirs(outdir, exist_ok=True)

# HiPS2FITS 服务与 SDSS DR9 r 波段 HiPS
HIPS2FITS = "https://alasky.cds.unistra.fr/hips-image-services/hips2fits"
HIPS_SDSS_R = "CDS/P/SDSS9/r"   # 也可换成 "CDS/P/SDSS9/g", "CDS/P/SDSS9/i"

In [3]:
# === Cell 1: imports & paths ===
import os, re, math, numpy as np, pandas as pd, requests
from astropy.io import fits
from astropy.wcs import WCS
from astropy.wcs.utils import proj_plane_pixel_scales

# 你的路径
rc3_tsv    = r"E:\NUS\galaxy\rc3\asu2.tsv"                 # RC3 TSV (VizieR 导出)
outdir     = r"E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4"  # 总输出目录
report_csv = r"E:\NUS\galaxy\rc3\centered_check_report4.csv"
os.makedirs(outdir, exist_ok=True)

# 选择 SDSS DR9 的五个波段（SDSS 无 b 波段）
BANDS = ['u', 'g', 'r', 'i', 'z']

# HiPS2FITS 服务与 SDSS DR9 HiPS 集合（不同 band 仅最后一段不同）
HIPS2FITS = "https://alasky.cds.unistra.fr/hips-image-services/hips2fits"
HIPS_SDSS = {b: f"CDS/P/SDSS9/{b}" for b in BANDS}

# 为每个波段创建单独输出子目录（可选）
band_outdirs = {b: os.path.join(outdir, b) for b in BANDS}
for d in band_outdirs.values():
    os.makedirs(d, exist_ok=True)

# 小工具：根据目标名与波段生成输出文件名
def make_outpath(base_name: str, band: str) -> str:
    """
    base_name: 例如 'UGC_12889_0'（你后续代码里生成的目标名）
    band:      'u'/'g'/'r'/'i'/'z'
    return:    该 band 的 FITS 完整保存路径
    """
    return os.path.join(band_outdirs[band], f"{base_name}_{band}.fits")

In [4]:
# === Cell 2: load & clean RC3 TSV ===
rc3 = pd.read_csv(rc3_tsv, sep=";", comment="#")

# 强制转数值；无效坐标丢弃
rc3["_RAJ2000"] = pd.to_numeric(rc3["_RAJ2000"], errors="coerce")
rc3["_DEJ2000"] = pd.to_numeric(rc3["_DEJ2000"], errors="coerce")
rc3 = rc3.dropna(subset=["_RAJ2000", "_DEJ2000"]).reset_index(drop=True)

print(f"[INFO] RC3 rows: {len(rc3)}")
print(rc3.head())

[INFO] RC3 rows: 9999
   _RAJ2000   _DEJ2000      RA2000     DE2000          altname          PGC  \
0  0.007852  47.274382  00 00 01.8  +47 16 28   UGC 12889       PGC    2
1  0.036593  -6.374703  00 00 08.7  -06 22 29   MCG -1- 1- 16   PGC   12
2  0.089093  -2.610543  00 00 21.3  -02 36 38   MCG -1- 1- 20   PGC   23
3  0.094195 -80.791574  00 00 22.5  -80 47 30   ESO   12- 12    PGC   30
4  0.100348  39.499948  00 00 24.0  +39 30 00   UGC 12894       PGC   35

      type     T    D25    R25     BT BT_code     cz
0  .SBT3..   3.0   1.33   0.07                   NaN
1  .S..1P?   1.0   1.18   0.74                  6493
2  .E+..*.  -4.0   1.15   0.25                   NaN
3  PSXT4P.   4.0   1.19   0.07                  7900
4  .I..9..  10.0   0.96   0.00                   NaN

In [5]:
# === Cell 3: helpers ===
def sanitize_name(name: str, fallback: str):
    if not isinstance(name, str) or not name.strip():
        return fallback
    s = name.strip().replace(" ", "_")
    # 仅保留安全字符
    s = re.sub(r"[^A-Za-z0-9_\-+]", "_", s)
    return s if s else fallback

def d25_arcmin(row):
    if "D25" in row and pd.notna(row["D25"]):
        try:
            return 0.1 * (10.0 ** float(row["D25"]))  # RC3 定义
        except Exception:
            return np.nan
    return np.nan

def choose_fov_deg(row, min_arcmin=3.0, max_arcmin=30.0, scale_factor=4.0):
    """
    FoV（度）= max(min_arcmin, min(max_arcmin, scale_factor * A25)) / 60
    让星系直径约占 FoV 的 ~1/scale_factor
    """
    a25 = d25_arcmin(row)
    if np.isnan(a25):
        fov_arcmin = 5.0  # 无 D25 时默认 5'
    else:
        fov_arcmin = max(min_arcmin, min(max_arcmin, scale_factor * a25))
    return fov_arcmin / 60.0  # 转度

In [6]:
# === Cell 4: download via HiPS2FITS (SDSS r) ===
width, height = 64, 64   # 输出像素尺寸；像素尺度由 FoV/width 决定
session = requests.Session()
session.headers.update({"User-Agent": "rc3-sdss-cutouts/1.0"})

# 先少量测试；确认 OK 后，可去掉 .head(N) 全量下载
subset = rc3.head(150)

for i, row in subset.iterrows():
    ra, dec = float(row["_RAJ2000"]), float(row["_DEJ2000"])
    altname = sanitize_name(row.get("altname", ""), f"RC3_{i}")
    fov_deg = choose_fov_deg(row)  # FoV（度）

    fname = os.path.join(outdir, f"{altname}_{i}.fits")
    if os.path.exists(fname):
        print(f"[SKIP] {fname}")
        continue

    params = {
        "hips": HIPS_SDSS_R,
        "ra": ra, "dec": dec,
        "width": width, "height": height,
        "fov": fov_deg,
        "projection": "TAN",
        "format": "fits",
        "coordsys": "icrs",
    }

    try:
        r = session.get(HIPS2FITS, params=params, timeout=90)
        r.raise_for_status()
        with open(fname, "wb") as f:
            f.write(r.content)
        print(f"[OK] {fname}  FoV={fov_deg*60:.1f}'")
    except Exception as e:
        print(f"[FAIL] idx={i} {altname}  {e}")

[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12889_0.fits  FoV=8.6'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\MCG_-1-_1-_16_1.fits  FoV=6.1'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\MCG_-1-_1-_20_2.fits  FoV=5.7'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\ESO___12-_12_3.fits  FoV=6.2'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12894_4.fits  FoV=3.6'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12893_5.fits  FoV=6.8'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12892_6.fits  FoV=3.3'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\ESO__293-_27_7.fits  FoV=7.6'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12895_8.fits  FoV=3.2'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12897_9.fits  FoV=4.6'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12898_10.fits  FoV=3.6'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\MCG__5-_1-_21_11.fits  FoV=3.1'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\UGC_12899_12.fits  FoV=3.8'
[OK] E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\ESO__193-__9_13.fits  FoV=4.7'

KeyboardInterrupt:

In [9]:
# === Cell 4: download via HiPS2FITS (SDSS u,g,r,i,z) ===
width, height = 64, 64   # 输出像素尺寸；像素尺度由 FoV/width 决定
session = requests.Session()
session.headers.update({"User-Agent": "rc3-sdss-cutouts/1.0"})

# 先少量测试；确认 OK 后，可去掉 .head(N) 全量下载
subset = rc3.head(150)

for i, row in subset.iterrows():
    ra, dec = float(row["_RAJ2000"]), float(row["_DEJ2000"])
    altname = sanitize_name(row.get("altname", ""), f"RC3_{i}")
    fov_deg = choose_fov_deg(row)  # FoV（度）
    base = f"{altname}_{i}"        # 统一的基础名，便于多波段区分

    for band in BANDS:  # e.g., ['u','g','r','i','z']
        hips_id = HIPS_SDSS[band]
        fname = make_outpath(base, band)  # 如 .../r/UGC_12889_0_r.fits

        if os.path.exists(fname):
            print(f"[SKIP] {band} {fname}")
            continue

        params = {
            "hips": hips_id,
            "ra": ra, "dec": dec,
            "width": width, "height": height,
            "fov": fov_deg,
            "projection": "TAN",
            "format": "fits",
            "coordsys": "icrs",
        }

        try:
            r = session.get(HIPS2FITS, params=params, timeout=90)
            r.raise_for_status()
            with open(fname, "wb") as f:
                f.write(r.content)
            print(f"[OK] {band} {fname}  FoV={fov_deg*60:.1f}'")
        except Exception as e:
            print(f"[FAIL] {band} idx={i} {altname}  {e}")

[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12889_0_u.fits  FoV=8.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12889_0_g.fits  FoV=8.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12889_0_r.fits  FoV=8.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12889_0_i.fits  FoV=8.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12889_0_z.fits  FoV=8.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_16_1_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_16_1_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_16_1_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_16_1_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_16_1_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_20_2_u.fits  FoV=5.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_20_2_g.fits  FoV=5.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_20_2_r.fits  FoV=5.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_20_2_i.fits  FoV=5.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_20_2_z.fits  FoV=5.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO___12-_12_3_u.fits  FoV=6.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO___12-_12_3_g.fits  FoV=6.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO___12-_12_3_r.fits  FoV=6.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO___12-_12_3_i.fits  FoV=6.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO___12-_12_3_z.fits  FoV=6.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12894_4_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12894_4_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12894_4_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12894_4_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12894_4_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12893_5_u.fits  FoV=6.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12893_5_g.fits  FoV=6.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12893_5_r.fits  FoV=6.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12893_5_i.fits  FoV=6.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12893_5_z.fits  FoV=6.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12892_6_u.fits  FoV=3.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12892_6_g.fits  FoV=3.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12892_6_r.fits  FoV=3.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12892_6_i.fits  FoV=3.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12892_6_z.fits  FoV=3.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__293-_27_7_u.fits  FoV=7.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__293-_27_7_g.fits  FoV=7.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__293-_27_7_r.fits  FoV=7.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__293-_27_7_i.fits  FoV=7.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__293-_27_7_z.fits  FoV=7.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12895_8_u.fits  FoV=3.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12895_8_g.fits  FoV=3.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12895_8_r.fits  FoV=3.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12895_8_i.fits  FoV=3.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12895_8_z.fits  FoV=3.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12897_9_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12897_9_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12897_9_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12897_9_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12897_9_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12898_10_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12898_10_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12898_10_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12898_10_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12898_10_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__5-_1-_21_11_u.fits  FoV=3.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__5-_1-_21_11_g.fits  FoV=3.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__5-_1-_21_11_r.fits  FoV=3.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__5-_1-_21_11_i.fits  FoV=3.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__5-_1-_21_11_z.fits  FoV=3.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12899_12_u.fits  FoV=3.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12899_12_g.fits  FoV=3.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12899_12_r.fits  FoV=3.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12899_12_i.fits  FoV=3.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12899_12_z.fits  FoV=3.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-__9_13_u.fits  FoV=4.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-__9_13_g.fits  FoV=4.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-__9_13_r.fits  FoV=4.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-__9_13_i.fits  FoV=4.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-__9_13_z.fits  FoV=4.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__293-_29_14_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__293-_29_14_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__293-_29_14_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__293-_29_14_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__293-_29_14_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12900_15_u.fits  FoV=7.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12900_15_g.fits  FoV=7.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12900_15_r.fits  FoV=7.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12900_15_i.fits  FoV=7.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12900_15_z.fits  FoV=7.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_17_16_u.fits  FoV=4.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_17_16_g.fits  FoV=4.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_17_16_r.fits  FoV=4.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_17_16_i.fits  FoV=4.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_17_16_z.fits  FoV=4.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__241-_10_17_u.fits  FoV=5.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__241-_10_17_g.fits  FoV=5.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__241-_10_17_r.fits  FoV=5.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__241-_10_17_i.fits  FoV=5.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__241-_10_17_z.fits  FoV=5.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12901_18_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12901_18_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12901_18_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12901_18_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12901_18_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__1-_1-_10_19_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__1-_1-_10_19_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__1-_1-_10_19_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__1-_1-_10_19_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__1-_1-_10_19_z.fits  FoV=3.0'

[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__1-_1-__9_20_u.fits  FoV=3.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__1-_1-__9_20_g.fits  FoV=3.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__1-_1-__9_20_r.fits  FoV=3.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__1-_1-__9_20_i.fits  FoV=3.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__1-_1-__9_20_z.fits  FoV=3.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12902_21_u.fits  FoV=4.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12902_21_g.fits  FoV=4.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12902_21_r.fits  FoV=4.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12902_21_i.fits  FoV=4.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12902_21_z.fits  FoV=4.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__2-_1-__9_22_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__2-_1-__9_22_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__2-_1-__9_22_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__2-_1-__9_22_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__2-_1-__9_22_z.fits  FoV=3.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12904_23_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12904_23_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12904_23_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12904_23_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12904_23_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12905_24_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12905_24_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12905_24_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12905_24_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12905_24_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12903_25_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12903_25_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12903_25_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12903_25_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12903_25_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__149-_12_26_u.fits  FoV=5.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__149-_12_26_g.fits  FoV=5.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__149-_12_26_r.fits  FoV=5.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__149-_12_26_i.fits  FoV=5.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__149-_12_26_z.fits  FoV=5.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__409-__1_27_u.fits  FoV=4.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__409-__1_27_g.fits  FoV=4.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__409-__1_27_r.fits  FoV=4.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__409-__1_27_i.fits  FoV=4.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__409-__1_27_z.fits  FoV=4.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12906_28_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12906_28_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12906_28_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12906_28_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12906_28_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12909_29_u.fits  FoV=8.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12909_29_g.fits  FoV=8.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12909_29_r.fits  FoV=8.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12909_29_i.fits  FoV=8.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12909_29_z.fits  FoV=8.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__2-_1-_12_30_u.fits  FoV=3.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__2-_1-_12_30_g.fits  FoV=3.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__2-_1-_12_30_r.fits  FoV=3.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__2-_1-_12_30_i.fits  FoV=3.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__2-_1-_12_30_z.fits  FoV=3.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12908_31_u.fits  FoV=4.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12908_31_g.fits  FoV=4.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12908_31_r.fits  FoV=4.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12908_31_i.fits  FoV=4.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12908_31_z.fits  FoV=4.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12910_32_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12910_32_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12910_32_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12910_32_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12910_32_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12911_33_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12911_33_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12911_33_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12911_33_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12911_33_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12912_34_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12912_34_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12912_34_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12912_34_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12912_34_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_498-_66_35_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_498-_66_35_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_498-_66_35_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_498-_66_35_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_498-_66_35_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12914_36_u.fits  FoV=9.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12914_36_g.fits  FoV=9.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12914_36_r.fits  FoV=9.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12914_36_i.fits  FoV=9.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12914_36_z.fits  FoV=9.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_477-_39_37_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_477-_39_37_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_477-_39_37_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_477-_39_37_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_477-_39_37_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12913_38_u.fits  FoV=5.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12913_38_g.fits  FoV=5.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12913_38_r.fits  FoV=5.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12913_38_i.fits  FoV=5.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12913_38_z.fits  FoV=5.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12915_39_u.fits  FoV=6.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12915_39_g.fits  FoV=6.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12915_39_r.fits  FoV=6.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12915_39_i.fits  FoV=6.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12915_39_z.fits  FoV=6.2'

[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_19_40_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_19_40_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_19_40_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_19_40_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_19_40_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__409-__3_41_u.fits  FoV=5.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__409-__3_41_g.fits  FoV=5.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__409-__3_41_r.fits  FoV=5.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__409-__3_41_i.fits  FoV=5.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__409-__3_41_z.fits  FoV=5.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-3-_1-_15_42_u.fits  FoV=30.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-3-_1-_15_42_g.fits  FoV=30.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-3-_1-_15_42_r.fits  FoV=30.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-3-_1-_15_42_i.fits  FoV=30.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-3-_1-_15_42_z.fits  FoV=30.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12916_43_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12916_43_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12916_43_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12916_43_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12916_43_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12917_44_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12917_44_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12917_44_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12917_44_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12917_44_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_20_45_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_20_45_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_20_45_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_20_45_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_20_45_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12918_46_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12918_46_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12918_46_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12918_46_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12918_46_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__0-_1-_19_47_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__0-_1-_19_47_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__0-_1-_19_47_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__0-_1-_19_47_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__0-_1-_19_47_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-7-_1-__8_48_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-7-_1-__8_48_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-7-_1-__8_48_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-7-_1-__8_48_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-7-_1-__8_48_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12919_49_u.fits  FoV=4.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12919_49_g.fits  FoV=4.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12919_49_r.fits  FoV=4.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12919_49_i.fits  FoV=4.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12919_49_z.fits  FoV=4.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_12920_50_u.fits  FoV=4.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_12920_50_g.fits  FoV=4.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_12920_50_r.fits  FoV=4.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_12920_50_i.fits  FoV=4.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_12920_50_z.fits  FoV=4.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__0-_1-_20_51_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__0-_1-_20_51_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__0-_1-_20_51_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__0-_1-_20_51_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__0-_1-_20_51_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____2_52_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____2_52_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____2_52_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____2_52_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____2_52_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_24_53_u.fits  FoV=4.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_24_53_g.fits  FoV=4.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_24_53_r.fits  FoV=4.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_24_53_i.fits  FoV=4.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_24_53_z.fits  FoV=4.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__1-_1-_13_54_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__1-_1-_13_54_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__1-_1-_13_54_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__1-_1-_13_54_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__1-_1-_13_54_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO___12-_14_55_u.fits  FoV=9.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO___12-_14_55_g.fits  FoV=9.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO___12-_14_55_r.fits  FoV=9.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO___12-_14_55_i.fits  FoV=9.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO___12-_14_55_z.fits  FoV=9.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____3_56_u.fits  FoV=6.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____3_56_g.fits  FoV=6.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____3_56_r.fits  FoV=6.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____3_56_i.fits  FoV=6.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____3_56_z.fits  FoV=6.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__149-_13_57_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__149-_13_57_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__149-_13_57_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__149-_13_57_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__149-_13_57_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__5-_1-_27_58_u.fits  FoV=3.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__5-_1-_27_58_g.fits  FoV=3.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__5-_1-_27_58_r.fits  FoV=3.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__5-_1-_27_58_i.fits  FoV=3.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__5-_1-_27_58_z.fits  FoV=3.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_21_59_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_21_59_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_21_59_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_21_59_i.fits  FoV=4.4'

[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_21_59_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____4_60_u.fits  FoV=4.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____4_60_g.fits  FoV=4.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____4_60_r.fits  FoV=4.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____4_60_i.fits  FoV=4.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____4_60_z.fits  FoV=4.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__293-_31_61_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__293-_31_61_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__293-_31_61_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__293-_31_61_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__293-_31_61_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____5_62_u.fits  FoV=7.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____5_62_g.fits  FoV=7.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____5_62_r.fits  FoV=7.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____5_62_i.fits  FoV=7.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____5_62_z.fits  FoV=7.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_498-_68_63_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_498-_68_63_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_498-_68_63_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_498-_68_63_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_498-_68_63_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____6_64_u.fits  FoV=3.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____6_64_g.fits  FoV=3.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____6_64_r.fits  FoV=3.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____6_64_i.fits  FoV=3.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____6_64_z.fits  FoV=3.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_477-_44_65_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_477-_44_65_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_477-_44_65_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_477-_44_65_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_477-_44_65_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_66_66_u.fits  FoV=6.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_66_66_g.fits  FoV=6.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_66_66_r.fits  FoV=6.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_66_66_i.fits  FoV=6.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_66_66_z.fits  FoV=6.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____7_67_u.fits  FoV=5.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____7_67_g.fits  FoV=5.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____7_67_r.fits  FoV=5.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____7_67_i.fits  FoV=5.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____7_67_z.fits  FoV=5.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_22_68_u.fits  FoV=4.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_22_68_g.fits  FoV=4.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_22_68_r.fits  FoV=4.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_22_68_i.fits  FoV=4.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_22_68_z.fits  FoV=4.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC_____8_69_u.fits  FoV=22.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC_____8_69_g.fits  FoV=22.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC_____8_69_r.fits  FoV=22.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC_____8_69_i.fits  FoV=22.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC_____8_69_z.fits  FoV=22.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_12_70_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_12_70_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_12_70_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_12_70_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_12_70_z.fits  FoV=3.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____12_71_u.fits  FoV=3.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____12_71_g.fits  FoV=3.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____12_71_r.fits  FoV=3.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____12_71_i.fits  FoV=3.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____12_71_z.fits  FoV=3.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____10_72_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____10_72_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____10_72_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____10_72_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____10_72_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____11_73_u.fits  FoV=3.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____11_73_g.fits  FoV=3.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____11_73_r.fits  FoV=3.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____11_73_i.fits  FoV=3.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____11_73_z.fits  FoV=3.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_11_74_u.fits  FoV=6.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_11_74_g.fits  FoV=6.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_11_74_r.fits  FoV=6.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_11_74_i.fits  FoV=6.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_11_74_z.fits  FoV=6.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__149-_15_75_u.fits  FoV=4.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__149-_15_75_g.fits  FoV=4.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__149-_15_75_r.fits  FoV=4.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__149-_15_75_i.fits  FoV=4.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__149-_15_75_z.fits  FoV=4.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____13_76_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____13_76_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____13_76_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____13_76_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____13_76_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_13_77_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_13_77_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_13_77_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_13_77_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_13_77_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____14_78_u.fits  FoV=7.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____14_78_g.fits  FoV=7.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____14_78_r.fits  FoV=7.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____14_78_i.fits  FoV=7.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____14_78_z.fits  FoV=7.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____17_79_u.fits  FoV=9.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____17_79_g.fits  FoV=9.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____17_79_r.fits  FoV=9.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____17_79_i.fits  FoV=9.8'

[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____17_79_z.fits  FoV=9.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____15_80_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____15_80_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____15_80_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____15_80_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____15_80_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____16_81_u.fits  FoV=6.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____16_81_g.fits  FoV=6.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____16_81_r.fits  FoV=6.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____16_81_i.fits  FoV=6.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____16_81_z.fits  FoV=6.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____19_82_u.fits  FoV=14.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____19_82_g.fits  FoV=14.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____19_82_r.fits  FoV=14.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____19_82_i.fits  FoV=14.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____19_82_z.fits  FoV=14.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_15_83_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_15_83_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_15_83_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_15_83_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_15_83_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_14_84_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_14_84_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_14_84_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_14_84_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_14_84_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____21_85_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____21_85_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____21_85_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____21_85_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____21_85_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_86_86_u.fits  FoV=5.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_86_86_g.fits  FoV=5.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_86_86_r.fits  FoV=5.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_86_86_i.fits  FoV=5.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_86_86_z.fits  FoV=5.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_14_87_u.fits  FoV=3.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_14_87_g.fits  FoV=3.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_14_87_r.fits  FoV=3.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_14_87_i.fits  FoV=3.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_14_87_z.fits  FoV=3.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____22_88_u.fits  FoV=5.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____22_88_g.fits  FoV=5.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____22_88_r.fits  FoV=5.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____22_88_i.fits  FoV=5.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____22_88_z.fits  FoV=5.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____23_89_u.fits  FoV=5.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____23_89_g.fits  FoV=5.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____23_89_r.fits  FoV=5.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____23_89_i.fits  FoV=5.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____23_89_z.fits  FoV=5.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____24_90_u.fits  FoV=3.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____24_90_g.fits  FoV=3.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____24_90_r.fits  FoV=3.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____24_90_i.fits  FoV=3.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____24_90_z.fits  FoV=3.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____25_91_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____25_91_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____25_91_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____25_91_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____25_91_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____26_92_u.fits  FoV=6.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____26_92_g.fits  FoV=6.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____26_92_r.fits  FoV=6.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____26_92_i.fits  FoV=6.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____26_92_z.fits  FoV=6.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____27_93_u.fits  FoV=7.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____27_93_g.fits  FoV=7.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____27_93_r.fits  FoV=7.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____27_93_i.fits  FoV=7.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____27_93_z.fits  FoV=7.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____28_94_u.fits  FoV=5.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____28_94_g.fits  FoV=5.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____28_94_r.fits  FoV=5.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____28_94_i.fits  FoV=5.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____28_94_z.fits  FoV=5.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____30_95_u.fits  FoV=4.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____30_95_g.fits  FoV=4.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____30_95_r.fits  FoV=4.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____30_95_i.fits  FoV=4.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____30_95_z.fits  FoV=4.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_28_96_u.fits  FoV=9.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_28_96_g.fits  FoV=9.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_28_96_r.fits  FoV=9.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_28_96_i.fits  FoV=9.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_28_96_z.fits  FoV=9.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____29_97_u.fits  FoV=5.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____29_97_g.fits  FoV=5.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____29_97_r.fits  FoV=5.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____29_97_i.fits  FoV=5.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____29_97_z.fits  FoV=5.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__241-_12_98_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__241-_12_98_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__241-_12_98_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__241-_12_98_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__241-_12_98_z.fits  FoV=3.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_30_99_u.fits  FoV=5.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_30_99_g.fits  FoV=5.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_30_99_r.fits  FoV=5.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_30_99_i.fits  FoV=5.7'

[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_30_99_z.fits  FoV=5.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__409-_12_100_u.fits  FoV=4.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__409-_12_100_g.fits  FoV=4.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__409-_12_100_r.fits  FoV=4.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__409-_12_100_i.fits  FoV=4.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__409-_12_100_z.fits  FoV=4.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_477-_49_101_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_477-_49_101_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_477-_49_101_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_477-_49_101_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_477-_49_101_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-3-_1-_18_102_u.fits  FoV=5.9'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-3-_1-_18_102_g.fits  FoV=5.9'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-3-_1-_18_102_r.fits  FoV=5.9'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-3-_1-_18_102_i.fits  FoV=5.9'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-3-_1-_18_102_z.fits  FoV=5.9'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__111-_12_103_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__111-_12_103_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__111-_12_103_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__111-_12_103_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__111-_12_103_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__0-_1-_25_104_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__0-_1-_25_104_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__0-_1-_25_104_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__0-_1-_25_104_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__0-_1-_25_104_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__0-_1-_24_105_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__0-_1-_24_105_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__0-_1-_24_105_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__0-_1-_24_105_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__0-_1-_24_105_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__149-_16_106_u.fits  FoV=4.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__149-_16_106_g.fits  FoV=4.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__149-_16_106_r.fits  FoV=4.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__149-_16_106_i.fits  FoV=4.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__149-_16_106_z.fits  FoV=4.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____31_107_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____31_107_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____31_107_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____31_107_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____31_107_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__241-_13_108_u.fits  FoV=4.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__241-_13_108_g.fits  FoV=4.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__241-_13_108_r.fits  FoV=4.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__241-_13_108_i.fits  FoV=4.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__241-_13_108_z.fits  FoV=4.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__409-_13_109_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__409-_13_109_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__409-_13_109_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__409-_13_109_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__409-_13_109_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____33_110_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____33_110_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____33_110_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____33_110_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____33_110_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____34_111_u.fits  FoV=6.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____34_111_g.fits  FoV=6.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____34_111_r.fits  FoV=6.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____34_111_i.fits  FoV=6.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____34_111_z.fits  FoV=6.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\CGCG_478-_23_112_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\CGCG_478-_23_112_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\CGCG_478-_23_112_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\CGCG_478-_23_112_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\CGCG_478-_23_112_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_17_113_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_17_113_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_17_113_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_17_113_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_17_113_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_19_114_u.fits  FoV=6.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_19_114_g.fits  FoV=6.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_19_114_r.fits  FoV=6.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_19_114_i.fits  FoV=6.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_19_114_z.fits  FoV=6.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____35_115_u.fits  FoV=6.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____35_115_g.fits  FoV=6.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____35_115_r.fits  FoV=6.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____35_115_i.fits  FoV=6.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____35_115_z.fits  FoV=6.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____36_116_u.fits  FoV=5.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____36_116_g.fits  FoV=5.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____36_116_r.fits  FoV=5.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____36_116_i.fits  FoV=5.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____36_116_z.fits  FoV=5.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-3-_1-_19_117_u.fits  FoV=5.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-3-_1-_19_117_g.fits  FoV=5.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-3-_1-_19_117_r.fits  FoV=5.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-3-_1-_19_117_i.fits  FoV=5.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-3-_1-_19_117_z.fits  FoV=5.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____37_118_u.fits  FoV=4.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____37_118_g.fits  FoV=4.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____37_118_r.fits  FoV=4.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____37_118_i.fits  FoV=4.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____37_118_z.fits  FoV=4.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____38_119_u.fits  FoV=4.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____38_119_g.fits  FoV=4.8'

[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____38_119_r.fits  FoV=4.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____38_119_i.fits  FoV=4.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____38_119_z.fits  FoV=4.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__5-_1-_31_120_u.fits  FoV=3.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__5-_1-_31_120_g.fits  FoV=3.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__5-_1-_31_120_r.fits  FoV=3.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__5-_1-_31_120_i.fits  FoV=3.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__5-_1-_31_120_z.fits  FoV=3.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_19_121_u.fits  FoV=7.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_19_121_g.fits  FoV=7.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_19_121_r.fits  FoV=7.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_19_121_i.fits  FoV=7.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_19_121_z.fits  FoV=7.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_18_122_u.fits  FoV=5.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_18_122_g.fits  FoV=5.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_18_122_r.fits  FoV=5.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_18_122_i.fits  FoV=5.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_18_122_z.fits  FoV=5.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____39_123_u.fits  FoV=4.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____39_123_g.fits  FoV=4.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____39_123_r.fits  FoV=4.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____39_123_i.fits  FoV=4.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____39_123_z.fits  FoV=4.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_124_124_u.fits  FoV=7.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_124_124_g.fits  FoV=7.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_124_124_r.fits  FoV=7.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_124_124_i.fits  FoV=7.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_124_124_z.fits  FoV=7.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____40_125_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____40_125_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____40_125_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____40_125_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____40_125_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_22_126_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_22_126_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_22_126_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_22_126_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_22_126_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____41_127_u.fits  FoV=4.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____41_127_g.fits  FoV=4.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____41_127_r.fits  FoV=4.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____41_127_i.fits  FoV=4.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____41_127_z.fits  FoV=4.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_27_128_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_27_128_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_27_128_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_27_128_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_27_128_z.fits  FoV=3.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__349-_26D_129_u.fits  FoV=4.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__349-_26D_129_g.fits  FoV=4.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__349-_26D_129_r.fits  FoV=4.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__349-_26D_129_i.fits  FoV=4.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__349-_26D_129_z.fits  FoV=4.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_22_130_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_22_130_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_22_130_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_22_130_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_22_130_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____42_131_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____42_131_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____42_131_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____42_131_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____42_131_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____43_132_u.fits  FoV=4.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____43_132_g.fits  FoV=4.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____43_132_r.fits  FoV=4.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____43_132_i.fits  FoV=4.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____43_132_z.fits  FoV=4.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__193-_23_133_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__193-_23_133_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__193-_23_133_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__193-_23_133_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__193-_23_133_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____44_134_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____44_134_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____44_134_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____44_134_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____44_134_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____45_135_u.fits  FoV=3.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____45_135_g.fits  FoV=3.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____45_135_r.fits  FoV=3.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____45_135_i.fits  FoV=3.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____45_135_z.fits  FoV=3.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG__1-_1-_29_136_u.fits  FoV=4.4'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG__1-_1-_29_136_g.fits  FoV=4.4'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG__1-_1-_29_136_r.fits  FoV=4.4'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG__1-_1-_29_136_i.fits  FoV=4.4'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG__1-_1-_29_136_z.fits  FoV=4.4'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_137_137_u.fits  FoV=7.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_137_137_g.fits  FoV=7.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_137_137_r.fits  FoV=7.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_137_137_i.fits  FoV=7.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_137_137_z.fits  FoV=7.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_138_138_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_138_138_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_138_138_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_138_138_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_138_138_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\ESO__293-_34_139_u.fits  FoV=12.6'

[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\ESO__293-_34_139_g.fits  FoV=12.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\ESO__293-_34_139_r.fits  FoV=12.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\ESO__293-_34_139_i.fits  FoV=12.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\ESO__293-_34_139_z.fits  FoV=12.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____46_140_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____46_140_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____46_140_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____46_140_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____46_140_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-7-_1-_10_141_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-7-_1-_10_141_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-7-_1-_10_141_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-7-_1-_10_141_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-7-_1-_10_141_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_25B_142_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_25B_142_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_25B_142_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_25B_142_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_25B_142_z.fits  FoV=3.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-1-_1-_33_143_u.fits  FoV=7.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-1-_1-_33_143_g.fits  FoV=7.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-1-_1-_33_143_r.fits  FoV=7.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-1-_1-_33_143_i.fits  FoV=7.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-1-_1-_33_143_z.fits  FoV=7.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\MCG_-2-_1-_25A_144_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\MCG_-2-_1-_25A_144_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\MCG_-2-_1-_25A_144_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\MCG_-2-_1-_25A_144_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\MCG_-2-_1-_25A_144_z.fits  FoV=3.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____47_145_u.fits  FoV=5.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____47_145_g.fits  FoV=5.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____47_145_r.fits  FoV=5.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____47_145_i.fits  FoV=5.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____47_145_z.fits  FoV=5.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____48_146_u.fits  FoV=6.1'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____48_146_g.fits  FoV=6.1'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____48_146_r.fits  FoV=6.1'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____48_146_i.fits  FoV=6.1'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____48_146_z.fits  FoV=6.1'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____49_147_u.fits  FoV=4.6'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____49_147_g.fits  FoV=4.6'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____49_147_r.fits  FoV=4.6'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____49_147_i.fits  FoV=4.6'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____49_147_z.fits  FoV=4.6'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\UGC____50_148_u.fits  FoV=3.7'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\UGC____50_148_g.fits  FoV=3.7'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\UGC____50_148_r.fits  FoV=3.7'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\UGC____50_148_i.fits  FoV=3.7'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\UGC____50_148_z.fits  FoV=3.7'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\u\RC3_149_149_u.fits  FoV=3.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\g\RC3_149_149_g.fits  FoV=3.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\r\RC3_149_149_r.fits  FoV=3.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\i\RC3_149_149_i.fits  FoV=3.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\z\RC3_149_149_z.fits  FoV=3.0'

In [7]:
# === Cell 4: download via HiPS2FITS (SDSS u,g,r,i,z) ===
width, height = 64, 64   # 输出像素尺寸；像素尺度由 FoV/width 决定
session = requests.Session()
session.headers.update({"User-Agent": "rc3-sdss-cutouts/1.0"})

# 取第160到第165个（含端点）
start_n, end_n = 160, 175
subset = rc3.reset_index(drop=True).iloc[start_n-1:end_n]
print(f"[INFO] 将下载第 {start_n}–{end_n} 个，共 {len(subset)} 条")

for i, row in subset.iterrows():
    ra, dec = float(row["_RAJ2000"]), float(row["_DEJ2000"])
    altname = sanitize_name(row.get("altname", ""), f"RC3_{i}")
    fov_deg = choose_fov_deg(row)  # FoV（度）
    base = f"{altname}_{i}"        # 统一的基础名，便于多波段区分

    for band in BANDS:  # e.g., ['u','g','r','i','z']
        hips_id = HIPS_SDSS[band]
        fname = make_outpath(base, band)  # 如 .../r/UGC_12889_0_r.fits

        if os.path.exists(fname):
            print(f"[SKIP] {band} {fname}")
            continue

        params = {
            "hips": hips_id,
            "ra": ra, "dec": dec,
            "width": width, "height": height,
            "fov": fov_deg,
            "projection": "TAN",
            "format": "fits",
            "coordsys": "icrs",
        }

        try:
            r = session.get(HIPS2FITS, params=params, timeout=90)
            r.raise_for_status()
            with open(fname, "wb") as f:
                f.write(r.content)
            print(f"[OK] {band} {fname}  FoV={fov_deg*60:.1f}'")
        except Exception as e:
            print(f"[FAIL] {band} idx={i} {altname}  {e}")

[INFO] 将下载第 160–175 个，共 16 条
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\RC3_159_159_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\RC3_159_159_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\RC3_159_159_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\RC3_159_159_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\RC3_159_159_z.fits
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____56_160_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____56_160_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____56_160_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____56_160_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____56_160_z.fits
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\ESO__293-_37_161_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\ESO__293-_37_161_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\ESO__293-_37_161_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\ESO__293-_37_161_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\ESO__293-_37_161_z.fits
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\ESO___12-_15_162_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\ESO___12-_15_162_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\ESO___12-_15_162_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\ESO___12-_15_162_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\ESO___12-_15_162_z.fits
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\ESO__538-_22_163_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\ESO__538-_22_163_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\ESO__538-_22_163_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\ESO__538-_22_163_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\ESO__538-_22_163_z.fits
[SKIP] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\ESO__149-_18_164_u.fits
[SKIP] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\ESO__149-_18_164_g.fits
[SKIP] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\ESO__149-_18_164_r.fits
[SKIP] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\ESO__149-_18_164_i.fits
[SKIP] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\ESO__149-_18_164_z.fits
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____57_165_u.fits  FoV=6.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____57_165_g.fits  FoV=6.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____57_165_r.fits  FoV=6.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____57_165_i.fits  FoV=6.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____57_165_z.fits  FoV=6.5'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____58_166_u.fits  FoV=4.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____58_166_g.fits  FoV=4.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____58_166_r.fits  FoV=4.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____58_166_i.fits  FoV=4.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____58_166_z.fits  FoV=4.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____59_167_u.fits  FoV=4.2'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____59_167_g.fits  FoV=4.2'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____59_167_r.fits  FoV=4.2'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____59_167_i.fits  FoV=4.2'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____59_167_z.fits  FoV=4.2'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____60_168_u.fits  FoV=7.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____60_168_g.fits  FoV=7.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____60_168_r.fits  FoV=7.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____60_168_i.fits  FoV=7.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____60_168_z.fits  FoV=7.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____61_169_u.fits  FoV=6.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____61_169_g.fits  FoV=6.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____61_169_r.fits  FoV=6.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____61_169_i.fits  FoV=6.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____61_169_z.fits  FoV=6.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\ESO__538-_23_170_u.fits  FoV=4.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\ESO__538-_23_170_g.fits  FoV=4.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\ESO__538-_23_170_r.fits  FoV=4.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\ESO__538-_23_170_i.fits  FoV=4.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\ESO__538-_23_170_z.fits  FoV=4.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\MCG_-2-_1-_27_171_u.fits  FoV=5.3'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\MCG_-2-_1-_27_171_g.fits  FoV=5.3'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\MCG_-2-_1-_27_171_r.fits  FoV=5.3'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\MCG_-2-_1-_27_171_i.fits  FoV=5.3'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\MCG_-2-_1-_27_171_z.fits  FoV=5.3'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\CGCG_477-_56_172_u.fits  FoV=5.0'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\CGCG_477-_56_172_g.fits  FoV=5.0'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\CGCG_477-_56_172_r.fits  FoV=5.0'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\CGCG_477-_56_172_i.fits  FoV=5.0'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\CGCG_477-_56_172_z.fits  FoV=5.0'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____62_173_u.fits  FoV=4.8'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____62_173_g.fits  FoV=4.8'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____62_173_r.fits  FoV=4.8'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____62_173_i.fits  FoV=4.8'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____62_173_z.fits  FoV=4.8'
[OK] u E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\u\UGC____63_174_u.fits  FoV=3.5'
[OK] g E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\g\UGC____63_174_g.fits  FoV=3.5'
[OK] r E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\r\UGC____63_174_r.fits  FoV=3.5'
[OK] i E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\i\UGC____63_174_i.fits  FoV=3.5'
[OK] z E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits4\z\UGC____63_174_z.fits  FoV=3.5'

In [23]:
# === Cell 5: centering check ===
fits_files = sorted([os.path.join(outdir, f) for f in os.listdir(outdir) if f.lower().endswith(".fits")])
rows = []
tol_5as, tol_30as = 5.0, 30.0

def parse_index_from_filename(name: str):
    m = re.search(r"_([0-9]+)\.fits$", name)
    return int(m.group(1)) if m else None

for path in fits_files:
    fname = os.path.basename(path)
    idx = parse_index_from_filename(fname)
    if idx is None or idx < 0 or idx >= len(rc3):
        rows.append(dict(file=fname, status="SKIP", note="no_valid_index"))
        continue

    ra = float(rc3.loc[idx, "_RAJ2000"])
    dec = float(rc3.loc[idx, "_DEJ2000"])
    altname = str(rc3.loc[idx, "altname"]).strip()

    try:
        with fits.open(path) as hdul:
            # 找 2D 图像平面
            hdu = next((h for h in hdul if h.data is not None and h.header.get("NAXIS",0) >= 2), None)
            if hdu is None:
                raise RuntimeError("No image HDU found")

            data = hdu.data
            w = WCS(hdu.header)

            H, W = int(data.shape[-2]), int(data.shape[-1])
            cx, cy = (W-1)/2.0, (H-1)/2.0

            # world -> pixel
            px, py = w.world_to_pixel_values(ra, dec)
            dx_pix, dy_pix = float(px - cx), float(py - cy)
            dr_pix = math.hypot(dx_pix, dy_pix)

            # 像素尺度（角秒/像素）
            sx_as, sy_as = (proj_plane_pixel_scales(w) * 3600.0)
            dx_as, dy_as = dx_pix * sx_as, dy_pix * sy_as
            dr_as = math.hypot(dx_as, dy_as)

            # 简单的“无覆盖/全零”判断
            invalid = False
            try:
                finite_ratio = np.isfinite(data).mean()
                nonzero_ratio = np.any(data != 0)
                if finite_ratio < 0.5 or not nonzero_ratio:
                    invalid = True
            except Exception:
                pass

            rows.append(dict(
                file=fname, idx=idx, altname=altname,
                ra=ra, dec=dec,
                dx_arcsec=dx_as, dy_arcsec=dy_as, dr_arcsec=dr_as,
                centered_le_5as = dr_as <= tol_5as,
                centered_le_30as = dr_as <= tol_30as,
                maybe_no_coverage = invalid,
                status="OK"
            ))

    except Exception as e:
        rows.append(dict(file=fname, idx=idx, altname=altname, ra=ra, dec=dec, status="ERROR", note=str(e)))

df = pd.DataFrame(rows)
df.to_csv(report_csv, index=False, float_format="%.3f", encoding="utf-8-sig")
print(f"[DONE] 写出报告: {report_csv}")

if "dr_arcsec" in df.columns:
    valid = df["dr_arcsec"].notna()
    rate5  = (df.loc[valid, "dr_arcsec"] <= tol_5as).mean() * 100
    rate30 = (df.loc[valid, "dr_arcsec"] <= tol_30as).mean() * 100
    print(f"Centered ≤5\": {rate5:.1f}%   |   ≤30\": {rate30:.1f}%")

    bad = df.loc[valid].sort_values("dr_arcsec", ascending=False).head(8)
    print("\n[Top off-center]")
    print(bad[["file","altname","dr_arcsec","dx_arcsec","dy_arcsec","maybe_no_coverage"]].to_string(index=False))

[DONE] 写出报告: E:\NUS\galaxy\rc3\centered_check_report2.csv

In [25]:
# === Cell 5: centering check (recursive + multi-band safe) ===
import os, re, math, numpy as np, pandas as pd
from astropy.io import fits
from astropy.wcs import WCS
from astropy.wcs.utils import proj_plane_pixel_scales

# 递归收集所有 .fits
fits_files = []
for root, _, files in os.walk(outdir):
    for f in files:
        if f.lower().endswith(".fits"):
            fits_files.append(os.path.join(root, f))
fits_files = sorted(fits_files)

rows = []
tol_5as, tol_30as = 5.0, 30.0

# 兼容两种命名：
# 1) 旧:  name_<idx>.fits
# 2) 新:  name_<idx>_<band>.fits  （例如 UGC_12889_0_r.fits）
pat_new = re.compile(r"_(\d+)_([ugriz])\.fits$", flags=re.I)
pat_old = re.compile(r"_(\d+)\.fits$", flags=re.I)

def parse_index_from_filename(name: str):
    m = pat_new.search(name)
    if m:
        return int(m.group(1))
    m = pat_old.search(name)
    if m:
        return int(m.group(1))
    return None

if len(fits_files) == 0:
    print(f"[WARN] 在 {outdir} 下未找到任何 FITS 文件。请确认 Cell 4 的输出路径与命名。")

for path in fits_files:
    fname = os.path.basename(path)
    idx = parse_index_from_filename(fname)
    if idx is None or idx < 0 or idx >= len(rc3):
        rows.append(dict(file=fname, status="SKIP", note="no_valid_index"))
        continue

    ra  = float(rc3.loc[idx, "_RAJ2000"])
    dec = float(rc3.loc[idx, "_DEJ2000"])
    altname = str(rc3.loc[idx, "altname"]).strip()

    try:
        with fits.open(path) as hdul:
            # 找 2D 图像平面
            hdu = next((h for h in hdul if (getattr(h, "data", None) is not None) and h.header.get("NAXIS", 0) >= 2), None)
            if hdu is None:
                raise RuntimeError("No image HDU found")

            data = np.asarray(hdu.data)
            H, W = int(data.shape[-2]), int(data.shape[-1])
            cx, cy = (W - 1) / 2.0, (H - 1) / 2.0

            # WCS（放宽并修复）
            w = WCS(hdu.header, relax=True)
            if not w.has_celestial:
                raise RuntimeError("WCS has no celestial component")

            # world -> pixel
            px, py = w.world_to_pixel_values(ra, dec)
            dx_pix, dy_pix = float(px - cx), float(py - cy)
            dr_pix = math.hypot(dx_pix, dy_pix)

            # 像素尺度（角秒/像素），必要时兜底
            try:
                sx_as, sy_as = (proj_plane_pixel_scales(w.celestial) * 3600.0)
            except Exception:
                # 兜底用 CDELT/CD
                cdelt1 = abs(hdu.header.get("CDELT1", np.nan))
                cdelt2 = abs(hdu.header.get("CDELT2", np.nan))
                if np.isfinite(cdelt1) and np.isfinite(cdelt2):
                    sx_as, sy_as = cdelt1 * 3600.0, cdelt2 * 3600.0
                else:
                    raise RuntimeError("Cannot determine pixel scale")

            dx_as, dy_as = dx_pix * sx_as, dy_pix * sy_as
            dr_as = math.hypot(dx_as, dy_as)

            # 简单覆盖性检查
            invalid = False
            try:
                finite_ratio = np.isfinite(data).mean()
                nonzero_any = bool(np.any((data != 0) & np.isfinite(data)))
                if finite_ratio < 0.5 or not nonzero_any:
                    invalid = True
            except Exception:
                pass

            rows.append(dict(
                file=fname, path=path, idx=idx, altname=altname,
                ra=ra, dec=dec,
                dx_arcsec=dx_as, dy_arcsec=dy_as, dr_arcsec=dr_as,
                centered_le_5as = dr_as <= tol_5as,
                centered_le_30as = dr_as <= tol_30as,
                maybe_no_coverage = invalid,
                status="OK"
            ))

    except Exception as e:
        rows.append(dict(file=fname, path=path, idx=idx, altname=altname, ra=ra, dec=dec,
                         status="ERROR", note=str(e)))

# 写出报告
df = pd.DataFrame(rows)
df.to_csv(report_csv, index=False, float_format="%.3f", encoding="utf-8-sig")
print(f"[DONE] 写出报告: {report_csv}  共 {len(df)} 行（含各波段文件）")

# 统计与预览
if "dr_arcsec" in df.columns and df["dr_arcsec"].notna().any():
    valid = df["dr_arcsec"].notna()
    rate5  = (df.loc[valid,  "dr_arcsec"] <= tol_5as ).mean() * 100
    rate30 = (df.loc[valid, "dr_arcsec"] <= tol_30as).mean() * 100
    print(f"Centered ≤5\": {rate5:.1f}%   |   ≤30\": {rate30:.1f}%")

    bad = df.loc[valid].sort_values("dr_arcsec", ascending=False).head(8)
    print("\n[Top off-center]")
    cols_show = [c for c in ["file","altname","dr_arcsec","dx_arcsec","dy_arcsec","maybe_no_coverage","status"] if c in bad.columns]
    print(bad[cols_show].to_string(index=False))
else:
    print("[WARN] 没有有效的 dr_arcsec 记录，可能没有解析到任何 FITS 或 WCS。")

[DONE] 写出报告: E:\NUS\galaxy\rc3\centered_check_report2.csv  共 750 行（含各波段文件）
Centered ≤5": 91.3%   |   ≤30": 100.0%

[Top off-center]
                   file       altname  dr_arcsec  dx_arcsec  dy_arcsec  maybe_no_coverage status
MCG_-3-_1-_15_42_i.fits MCG -3- 1- 15  19.887504 -14.062589 -14.062589               True     OK
MCG_-3-_1-_15_42_u.fits MCG -3- 1- 15  19.887504 -14.062589 -14.062589               True     OK
MCG_-3-_1-_15_42_r.fits MCG -3- 1- 15  19.887504 -14.062589 -14.062589               True     OK
MCG_-3-_1-_15_42_z.fits MCG -3- 1- 15  19.887504 -14.062589 -14.062589               True     OK
MCG_-3-_1-_15_42_g.fits MCG -3- 1- 15  19.887504 -14.062589 -14.062589               True     OK
    UGC_____8_69_z.fits     UGC     8  14.571953 -10.303926 -10.303926              False     OK
    UGC_____8_69_g.fits     UGC     8  14.571953 -10.303926 -10.303926              False     OK
    UGC_____8_69_u.fits     UGC     8  14.571953 -10.303926 -10.303926              False     OK

In [26]:
# === Cell 1: 路径与选项 ===
import os, shutil, pandas as pd

# 与之前保持一致
outdir      = r"E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3"   # FITS 输出目录
report_csv  = r"E:\NUS\galaxy\rc3\centered_check_report2.csv" # 评估报告
trash_dir   = os.path.join(outdir, "_no_coverage_quarantine") # 隔离文件夹

# True = 移动到隔离文件夹；False = 直接永久删除
SAFE_MOVE = True

os.makedirs(trash_dir, exist_ok=True)
print("[INFO] outdir =", outdir)
print("[INFO] report =", report_csv)
print("[INFO] trash_dir =", trash_dir, "(created)")
print("[INFO] mode =", "MOVE to quarantine" if SAFE_MOVE else "PERMANENT DELETE")

[INFO] outdir = E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3
[INFO] report = E:\NUS\galaxy\rc3\centered_check_report2.csv
[INFO] trash_dir = E:\NUS\galaxy\rc3\sdss_cutouts_hips2fits3\_no_coverage_quarantine (created)
[INFO] mode = MOVE to quarantine

In [27]:
# === Cell 2: 读取报告并筛选 ===
df = pd.read_csv(report_csv)
if "maybe_no_coverage" not in df.columns:
    raise RuntimeError("报告中没有列 `maybe_no_coverage`，请先运行评估步骤并生成该列。")

to_remove = df[df["maybe_no_coverage"] == True].copy()
print(f"[INFO] 标记为 'maybe_no_coverage==True' 的文件数：{len(to_remove)}")
to_remove[["file","altname","dr_arcsec"]].head(10)

[INFO] 标记为 'maybe_no_coverage==True' 的文件数：270

                       file       altname  dr_arcsec
6   ESO__111-_12_103_g.fits  ESO  111- 12      3.045
7    ESO__149-_12_26_g.fits  ESO  149- 12      3.577
8    ESO__149-_13_57_g.fits  ESO  149- 13      4.013
9    ESO__149-_15_75_g.fits  ESO  149- 15      2.713
10  ESO__149-_16_106_g.fits  ESO  149- 16      3.115
11   ESO__193-_11_74_g.fits  ESO  193- 11      4.107
12   ESO__193-_14_87_g.fits  ESO  193- 14      2.155
13  ESO__193-_17_113_g.fits  ESO  193- 17      2.363
14  ESO__193-_18_122_g.fits  ESO  193- 18      3.660
15  ESO__193-_19_121_g.fits  ESO  193- 19      5.170

In [28]:
# === Cell 2: 读取报告并筛选（无语法错误版） ===
import os
import pandas as pd

def _try_read(path):
    """尝试多种方式读取CSV或TSV，返回(df, 参数)"""
    tried = []
    read_options = [
        {"sep": ",", "engine": "c"},
        {"sep": None, "engine": "python"},
        {"sep": "\t", "engine": "python"},
        {"sep": ",", "engine": "python", "encoding": "utf-8-sig"},
        {"sep": "\t", "engine": "python", "encoding": "utf-8-sig"},
    ]
    for kwargs in read_options:
        try:
            df = pd.read_csv(path, **kwargs)
            if df is not None and len(df.columns) > 0:
                return df, kwargs
            tried.append(kwargs)
        except Exception as e:
            tried.append({**kwargs, "err": str(e)})
    raise RuntimeError(f"无法解析文件：{path}\n尝试方式：{tried}")

# === 1) 检查文件存在与大小 ===
if not os.path.exists(report_csv):
    raise FileNotFoundError(f"找不到报告文件：{report_csv}")

if os.path.getsize(report_csv) == 0:
    raise RuntimeError(
        f"报告文件为空：{report_csv}\n"
        f"请先运行居中评估步骤（centered_check），生成 maybe_no_coverage 列。"
    )

# === 2) 读取 ===
df, used_kwargs = _try_read(report_csv)
print(f"[INFO] 读取成功，使用参数：{used_kwargs}, 形状={df.shape}")

# === 3) 清洗列名 ===
df.columns = [c.strip() for c in df.columns]

# 标准化 maybe_no_coverage 列
if "maybe_no_coverage" in df.columns:
    if df["maybe_no_coverage"].dtype == object:
        df["maybe_no_coverage"] = (
            df["maybe_no_coverage"]
            .astype(str)
            .str.strip()
            .str.lower()
            .map({"true": True, "false": False, "1": True, "0": False})
            .fillna(False)
        )
else:
    # 兼容可能误写的列名
    alt_cols = [c for c in df.columns if c.replace(" ", "").lower() == "maybenocoverage"]
    if alt_cols:
        df.rename(columns={alt_cols[0]: "maybe_no_coverage"}, inplace=True)
    else:
        raise RuntimeError(
            "报告中没有列 `maybe_no_coverage`。\n"
            f"现有列：{list(df.columns)}"
        )

# === 4) 过滤 ===
to_remove = df[df["maybe_no_coverage"] == True].copy()
print(f"[INFO] 标记为 maybe_no_coverage==True 的文件数：{len(to_remove)}")

# === 5) 预览 ===
cols = [c for c in ["file", "altname", "dr_arcsec"] if c in to_remove.columns]
if cols:
    display(to_remove[cols].head(10))
else:
    print("[WARN] 预览列(file, altname, dr_arcsec)缺失，打印前几行：")
    print(to_remove.head(10))

[INFO] 读取成功，使用参数：{'sep': ',', 'engine': 'c'}, 形状=(750, 13)
[INFO] 标记为 maybe_no_coverage==True 的文件数：270

                       file       altname  dr_arcsec
6   ESO__111-_12_103_g.fits  ESO  111- 12      3.045
7    ESO__149-_12_26_g.fits  ESO  149- 12      3.577
8    ESO__149-_13_57_g.fits  ESO  149- 13      4.013
9    ESO__149-_15_75_g.fits  ESO  149- 15      2.713
10  ESO__149-_16_106_g.fits  ESO  149- 16      3.115
11   ESO__193-_11_74_g.fits  ESO  193- 11      4.107
12   ESO__193-_14_87_g.fits  ESO  193- 14      2.155
13  ESO__193-_17_113_g.fits  ESO  193- 17      2.363
14  ESO__193-_18_122_g.fits  ESO  193- 18      3.660
15  ESO__193-_19_121_g.fits  ESO  193- 19      5.170

In [29]:
# === Cell 3: 移除 ===
removed, missing = [], []

for fname in to_remove["file"]:
    src = os.path.join(outdir, fname)
    if not os.path.isfile(src):
        missing.append(fname)
        continue

    if SAFE_MOVE:
        dst = os.path.join(trash_dir, fname)
        # 目标存在则先加后缀避免覆盖
        if os.path.exists(dst):
            base, ext = os.path.splitext(dst)
            k = 1
            while os.path.exists(dst):
                dst = f"{base}__dup{k}{ext}"
                k += 1
        shutil.move(src, dst)
    else:
        os.remove(src)
    removed.append(fname)

print(f"[DONE] 已{'移动' if SAFE_MOVE else '删除'} {len(removed)} 个文件。")
if missing:
    print(f"[WARN] 下列文件在目录中未找到（可能之前已处理）：")
    for x in missing[:10]:
        print(" -", x)

[DONE] 已移动 0 个文件。
[WARN] 下列文件在目录中未找到（可能之前已处理）：
 - ESO__111-_12_103_g.fits
 - ESO__149-_12_26_g.fits
 - ESO__149-_13_57_g.fits
 - ESO__149-_15_75_g.fits
 - ESO__149-_16_106_g.fits
 - ESO__193-_11_74_g.fits
 - ESO__193-_14_87_g.fits
 - ESO__193-_17_113_g.fits
 - ESO__193-_18_122_g.fits
 - ESO__193-_19_121_g.fits